Repository PWEB-3-3-2022/back, pull requests merged in 2022-05, with the labels that each got.

#44 Use a cookie for the auth token
  package.json
  pnpm-lock.yaml
  src/app.js
  src/auth.js
  src/routes/auth.js
  src/routes/user.js
Labels: feature, security

#45 Use cookie-parser, update openapi docs
  package.json
  pnpm-lock.yaml
  src/app.js
  src/auth.js
  src/routes/auth.js
  src/routes/user.js
  src/swagger/defs.yml
Labels: documentation, feature

#47 Require auth on all endpoints
  src/app.js
  src/auth.js
  src/auth.test.js
  src/db/conn.js
  src/routes/home.js
  src/routes/medias.js
  src/routes/user.js
Labels: feature, security

#48 Create a download link on demand
  package.json
  pnpm-lock.yaml
  src/app.js
  src/backblaze.js
  src/routes/medias.js
Labels: feature

#55 Add services to separate logic from endpoints
  src/app.js
  src/db/schema.js
  src/routes/auth.js
  src/routes/home.js
  src/routes/medias.js
  src/routes/user.js
  src/services/auth.js
  src/services/backblaze.js
  src/services/home.js
  src/services/medias.js
  src/services/user.js
  src/utils.js
Labels: feature
